PROBLEMS = [
    {
        "id": "lv1_1",
        "level": "LV1",
        "type": "multiple_choice",
        "title": "요청 방식 확인",
        "question": "다음 코드는 사용자가 페이지에 접속했을 때와, 폼을 제출했을 때를 구분하기 위한 코드입니다.",
        "code": "if request._____ == 'POST':\n    print(\"제출 완료\")",
        "choices": ["route", "method", "score", "nickname"],
        "answer": "method",
        "hint": "사용자가 폼을 제출했는지 확인할 때는 요청의 방식을 확인해야 합니다. request.method",
        "explanation": "request.method는 사용자의 요청 방식이 무엇인지 확인할 때 사용합니다. 폼 제출은 보통 POST 방식으로 처리합니다.",
        "score": 1,
    },
    {
        "id": "lv1_2",
        "level": "LV1",
        "type": "multiple_choice",
        "title": "입력값 저장 위치",
        "question": "사용자가 HTML 입력창에 적은 값을 서버에서 가져오려고 합니다.",
        "code": "nickname = request._____.get('nickname', '')",
        "choices": ["form", "route", "print", "list"],
        "answer": "form",
        "hint": "HTML의 form 태그 안에서 보낸 값들은 request 안의 특정 공간에 저장됩니다. request.form",
        "explanation": "request.form은 폼으로 전달된 입력값들을 담고 있습니다.",
        "score": 1,
    },
    {
        "id": "lv1_3",
        "level": "LV1",
        "type": "multiple_choice",
        "title": "없는 점수 처리",
        "question": "MBTI 조합 점수가 점수표에 없을 때, 프로그램이 오류로 멈추지 않도록 기본 점수를 사용하려고 합니다.",
        "code": "general = COMPAT.get(mbti1, {}).get(mbti2, _____)",
        "choices": ["0", "10", "50", "100"],
        "answer": "50",
        "hint": "점수표에 없는 MBTI 조합은 너무 좋지도, 너무 나쁘지도 않은 중간 점수로 처리합니다. 0점과 100점의 가운데 값입니다.",
        "explanation": "점수표에 없는 조합이면 중간값에 가까운 기본 점수를 사용해 프로그램이 계속 실행되도록 합니다.",
        "score": 1,
    },
    {
        "id": "lv1_4",
        "level": "LV1",
        "type": "multiple_choice",
        "title": "가중 평균 계산",
        "question": "네 가지 점수를 합쳐 최종 점수를 만들려고 합니다. 일반 궁합 점수는 다른 항목보다 한 번 더 반영됩니다.",
        "code": "final_score = (general * _____ + relationship + conflict + expression) / 5",
        "choices": ["0", "1", "2", "10"],
        "answer": "2",
        "hint": "general 점수는 다른 점수보다 한 번 더 반영됩니다. 즉, 총 두 번 반영되는 셈입니다. general * 2",
        "explanation": "일반 궁합 점수를 두 번 반영하기 위해 general * 2를 사용합니다.",
        "score": 1,
    },
    {
        "id": "lv1_5",
        "level": "LV1",
        "type": "multiple_choice",
        "title": "점수 차이 계산",
        "question": "실제 점수와 예상 점수의 차이를 계산하려고 합니다. 결과는 항상 양수로 나오게 해야 합니다.",
        "code": "difference = _____(score - expected_score_float)",
        "choices": ["len", "abs", "str", "print"],
        "answer": "abs",
        "hint": "점수 차이는 음수가 나오면 안 됩니다. 파이썬에서 절댓값을 구하는 함수를 사용합니다. abs(...)",
        "explanation": "abs()는 음수를 양수로 바꾸는 절댓값 함수입니다. 점수 차이를 계산할 때 적합합니다.",
        "score": 1,
    },
    {
        "id": "lv2_1",
        "level": "LV2",
        "type": "short_answer",
        "title": "요청 방식 판별하기",
        "question": "다음 코드는 사용자의 요청이 제출 요청인지 확인하는 코드입니다. 빈칸에 들어갈 코드를 작성하세요.",
        "code": "from flask import request\n\nif request._____ == 'POST':\n    result = \"submitted\"",
        "choices": [],
        "answer": "method",
        "hint": "request 뒤에 붙여서 현재 요청 방식이 GET인지 POST인지 확인하는 속성입니다. request.method",
        "explanation": "request.method를 사용하면 현재 요청 방식이 GET인지 POST인지 확인할 수 있습니다.",
        "score": 3,
    },
    {
        "id": "lv2_2",
        "level": "LV2",
        "type": "short_answer",
        "title": "닉네임 가져오기",
        "question": "HTML에서 사용자가 닉네임을 입력했습니다.\n\n제공 HTML:\n<input name=\"nickname\">\n\n서버에서 이 값을 가져와 nickname 변수에 저장하려고 합니다. 빈칸에 들어갈 코드를 작성하세요.",
        "code": "nickname = request._____.get('nickname', '')",
        "choices": [],
        "answer": "form",
        "hint": "HTML form에서 전달된 값은 request 안의 이 공간에서 꺼냅니다. request.form.get(...)",
        "explanation": "폼 입력값은 request.form을 통해 가져올 수 있습니다.",
        "score": 3,
    },
    {
        "id": "lv2_3",
        "level": "LV2",
        "type": "short_answer",
        "title": "기본 점수 넣기",
        "question": "아래 점수표에서 INFP와 ISTP 조합은 등록되어 있지 않습니다. 등록되지 않은 조합이 들어와도 프로그램이 멈추지 않도록 빈칸을 채우세요.",
        "code": "COMPAT = {\n    'INFP': {\n        'ENFJ': 95,\n        'ESTJ': 60\n    }\n}\n\nmbti1 = 'INFP'\nmbti2 = 'ISTP'\n\ngeneral = COMPAT.get(mbti1, {}).get(mbti2, _____)",
        "choices": [],
        "answer": "50",
        "hint": "MBTI 조합이 점수표에 없을 때는 기본적으로 보통 궁합 정도로 처리합니다. 앱에서는 100점 만점 기준의 중간 점수를 사용합니다. .get(mbti2, 50)",
        "explanation": "점수표에 없는 조합일 때는 기본 점수를 사용합니다. 이 앱에서는 기본값으로 50을 사용합니다.",
        "score": 3,
    },
    {
        "id": "lv2_4",
        "level": "LV2",
        "type": "short_answer",
        "title": "최종 점수 계산식",
        "question": "다음 네 점수를 하나의 최종 점수로 합치려고 합니다.\n\n조건:\ngeneral은 두 번 반영한다.\n나머지 세 점수는 한 번씩 반영한다.\n전체 평균을 구한다.\n\n빈칸에 들어갈 숫자를 순서대로 작성하세요.",
        "code": "general = 90\nrelationship = 80\nconflict = 70\nexpression = 85\n\nfinal_score = (general * _____ + relationship + conflict + expression) / _____",
        "choices": [],
        "answer": "2,5",
        "hint": "general은 두 번 반영됩니다. 반영되는 항목 수를 세면 general, general, relationship, conflict, expression입니다. (general * 2 + relationship + conflict + expression) / 5",
        "explanation": "반영 횟수는 general 2번, 나머지 3개 항목 각각 1번이므로 총 5개 값의 평균을 구합니다.",
        "score": 3,
    },
    {
        "id": "lv2_5",
        "level": "LV2",
        "type": "short_answer",
        "title": "예상 점수 변환과 차이 계산",
        "question": "사용자가 입력한 예상 점수는 문자 형태로 들어옵니다. 이 값을 계산 가능한 숫자로 바꾼 뒤, 실제 점수와의 차이를 구하려고 합니다.\n\n빈칸에 들어갈 코드를 순서대로 작성하세요.",
        "code": "score = 82.5\nexpected_score = '90'\n\nexpected_score_float = _____(expected_score)\ndifference = _____(score - expected_score_float)",
        "choices": [],
        "answer": "float,abs",
        "hint": "첫 번째 빈칸에는 문자로 들어온 숫자를 계산 가능한 숫자로 바꾸는 함수가 들어갑니다. 두 번째 빈칸에는 결과를 항상 양수로 만드는 함수가 들어갑니다. float(...), abs(...)",
        "explanation": "float()는 문자 형태의 숫자를 소수형 숫자로 바꿉니다. abs()는 계산 결과가 음수여도 양수 차이값으로 바꿔줍니다.",
        "score": 3,
    },
    {
        "id": "lv3_1",
        "level": "LV3",
        "type": "code_answer",
        "title": "제출된 입력값 가져오기",
        "question": "다음 HTML 폼이 있다고 가정합니다.\n\nHTML:\n<select name=\"mbti1\"></select>\n<select name=\"mbti2\"></select>\n<input name=\"expected_score\">\n<input name=\"nickname\">\n\n조건:\n사용자가 제출한 네 값을 각각 변수에 저장한다.\n저장할 변수 이름: mbti1, mbti2, expected_score, nickname\nexpected_score와 nickname은 값이 없을 경우 빈 문자열이 저장되도록 한다.\n필요한 도구: from flask import request\n\n위 조건을 만족하는 코드를 작성하세요.",
        "code": "",
        "choices": [],
        "answer": "mbti1 = request.form.get('mbti1')\nmbti2 = request.form.get('mbti2')\nexpected_score = request.form.get('expected_score', '')\nnickname = request.form.get('nickname', '')",
        "hint": "mbti1 = request.form.get('mbti1')\nmbti2 = request.form.get('mbti2')\nexpected_score = request.form.get('expected_score', '')\nnickname = request.form.get('nickname', '')",
        "explanation": "HTML 폼에서 넘어온 값은 request.form.get()으로 가져올 수 있습니다. 두 번째 인자에 기본값을 넣으면 입력값이 없을 때 사용할 값을 정할 수 있습니다.",
        "score": 8,
    },
    {
        "id": "lv3_2",
        "level": "LV3",
        "type": "code_answer",
        "title": "MBTI 점수 4개 조회하기",
        "question": "아래 네 개의 점수표에서 mbti1, mbti2 조합에 해당하는 점수를 가져오세요. 등록되지 않은 조합은 기본 점수 50을 사용합니다. 저장할 변수 이름은 general, relationship, conflict, expression입니다.",
        "code": "COMPAT = {\n    'INFP': {'ENFJ': 95, 'ESTJ': 60},\n    'INTJ': {'ENFP': 90, 'ESFP': 55}\n}\n\nRELATIONSHIP = {\n    'INFP': {'ENFJ': 90, 'ESTJ': 65},\n    'INTJ': {'ENFP': 85, 'ESFP': 50}\n}\n\nCONFLICT = {\n    'INFP': {'ENFJ': 80, 'ESTJ': 45},\n    'INTJ': {'ENFP': 75, 'ESFP': 40}\n}\n\nEXPRESSION = {\n    'INFP': {'ENFJ': 85, 'ESTJ': 55},\n    'INTJ': {'ENFP': 80, 'ESFP': 45}\n}\n\nmbti1 = 'INFP'\nmbti2 = 'ENFJ'",
        "choices": [],
        "answer": "general = COMPAT.get(mbti1, {}).get(mbti2, 50)\nrelationship = RELATIONSHIP.get(mbti1, {}).get(mbti2, 50)\nconflict = CONFLICT.get(mbti1, {}).get(mbti2, 50)\nexpression = EXPRESSION.get(mbti1, {}).get(mbti2, 50)",
        "hint": "점수표.get(mbti1, {}).get(mbti2, 50)",
        "explanation": "이중 딕셔너리에서 값을 가져오는 문제입니다. .get()을 사용하면 등록되지 않은 값이 들어와도 오류를 줄일 수 있습니다.",
        "score": 8,
    },
    {
        "id": "lv3_3",
        "level": "LV3",
        "type": "code_answer",
        "title": "최종 점수 만들기",
        "question": "general은 두 번, relationship, conflict, expression은 한 번씩 반영합니다. 가중 평균을 final_score에 저장하고, score 변수에도 같은 값을 저장한 뒤, format_score를 사용한 결과를 score_display에 저장하세요.",
        "code": "general = 95\nrelationship = 90\nconflict = 80\nexpression = 85\n\ndef format_score(score):\n    return f\"{score:.1f}\"",
        "choices": [],
        "answer": "final_score = (general * 2 + relationship + conflict + expression) / 5\nscore = final_score\nscore_display = format_score(final_score)",
        "hint": "final_score = (general * 2 + relationship + conflict + expression) / 5\nscore = final_score\nscore_display = format_score(final_score)",
        "explanation": "일반 궁합 점수에 더 큰 비중을 두고, 네 종류의 점수를 하나의 최종 점수로 합치는 코드입니다.",
        "score": 8,
    },
    {
        "id": "lv3_4",
        "level": "LV3",
        "type": "code_answer",
        "title": "점수에 따라 결과 단계 정하기",
        "question": "최종 점수 score = 86이 주어져 있습니다. 점수에 따라 stage_emoji, stage_label, stage_description 세 변수를 정하세요.\n\n판정 기준:\n90~100: ❤️ / 운명 궁합\n80~89: 😊 / 찰떡 궁합\n70~79: 🙂 / 좋은 궁합\n50~69: 😐 / 무난한 궁합\n30~49: 😅 / 유의 궁합\n10~29: ⚠️ / 충돌 주의 궁합\n그 외: 💔 / 극과 극 궁합",
        "code": "score = 86",
        "choices": [],
        "answer": "if 90 <= score <= 100:\n    stage_emoji = '❤️'\n    stage_label = '운명 궁합'\n    stage_description = '서로의 장점이 강하게 살아나는 조합이에요.'\nelif 80 <= score <= 89:\n    stage_emoji = '😊'\n    stage_label = '찰떡 궁합'\n    stage_description = '서로를 존중하면 안정적인 관계가 될 수 있어요.'\nelse:\n    stage_emoji = '💔'\n    stage_label = '극과 극 궁합'\n    stage_description = '서로의 차이를 인정하는 태도가 필요해요.'",
        "hint": "if 90 <= score <= 100:\n    stage_emoji = '❤️'\n    stage_label = '운명 궁합'\nelif 80 <= score <= 89:\n    stage_emoji = '😊'\n    stage_label = '찰떡 궁합'\nelse:\n    stage_emoji = '💔'\n    stage_label = '극과 극 궁합'",
        "explanation": "조건문을 사용해 숫자 점수를 문자 결과로 바꾸는 코드입니다. 실제 앱에서는 이 결과가 화면에 표시됩니다.",
        "score": 8,
    },
    {
        "id": "lv3_5",
        "level": "LV3",
        "type": "code_answer",
        "title": "순위표에 결과 저장하기",
        "question": "현재 제출 데이터를 하나의 딕셔너리로 만들고, 새 결과가 순위표의 가장 앞쪽에 들어가게 하세요. 저장된 결과가 최대 개수를 초과하면 가장 오래된 결과 하나를 제거합니다.",
        "code": "nickname = '하람'\nexpected_score_float = 88.0\nscore = 86.0\ndifference = 2.0\n\ngeneral = 90\nrelationship = 85\nconflict = 80\nexpression = 85\n\nrankings = []\nMAX_RANKINGS = 100\n\nfrom uuid import uuid4",
        "choices": [],
        "answer": "current_entry_id = uuid4().hex\n\nranking_entry = {\n    'id': current_entry_id,\n    'nickname': nickname,\n    'expected_score': expected_score_float,\n    'final_score': score,\n    'difference': difference,\n    'general': general,\n    'relationship': relationship,\n    'conflict': conflict,\n    'expression': expression\n}\n\nrankings.insert(0, ranking_entry)\n\nif len(rankings) > MAX_RANKINGS:\n    rankings.pop()",
        "hint": "current_entry_id = uuid4().hex\nrankings.insert(0, ranking_entry)\n\nif len(rankings) > MAX_RANKINGS:\n    rankings.pop()",
        "explanation": "딕셔너리는 한 명의 제출 결과를 저장하고, 리스트는 여러 명의 결과를 저장합니다. 새 결과를 앞에 넣으면 최근 제출이 먼저 보이고, 개수가 너무 많아지면 마지막 데이터를 삭제합니다.",
        "score": 8,
    },
]


MISSIONS = {
    "A": {
        "id": "A",
        "title": "개발 미션 A: 기본형",
        "score": 8,
        "question": "아래 변수 score가 주어져 있습니다.\n\nscore = 85\n\n조건:\nscore가 80 이상이면 \"좋은 궁합\"을 출력하는 코드를 작성하세요.",
        "example": "score = 85\n\nif score >= 80:\n    print(\"좋은 궁합\")",
        "criteria": ["if 사용", "score >= 80 또는 같은 의미의 조건 사용", "\"좋은 궁합\" 출력"],
    },
    "B": {
        "id": "B",
        "title": "개발 미션 B: 보통형",
        "score": 12,
        "question": "아래 네 점수가 주어져 있습니다.\n\ngeneral = 90\nrelationship = 80\nconflict = 70\nexpression = 85\n\n조건:\ngeneral은 두 번 반영한다.\nrelationship, conflict, expression은 한 번씩 반영한다.\n최종 점수를 final_score에 저장한다.\nfinal_score를 출력한다.",
        "example": "general = 90\nrelationship = 80\nconflict = 70\nexpression = 85\n\nfinal_score = (general * 2 + relationship + conflict + expression) / 5\nprint(final_score)",
        "criteria": ["final_score 변수 사용", "general을 2배 반영", "전체를 5로 나눔", "print 사용"],
    },
    "C": {
        "id": "C",
        "title": "개발 미션 C: 도전형",
        "score": 20,
        "question": "아래 값들이 주어져 있습니다.\n\ngeneral = 90\nrelationship = 80\nconflict = 70\nexpression = 85\nexpected_score = \"88\"\n\n조건:\n1. general은 두 번 반영해 최종 점수를 계산한다.\n2. 예상 점수를 숫자로 바꾼다.\n3. 실제 점수와 예상 점수의 차이를 계산한다.\n4. 최종 점수가 90 이상이면 \"운명 궁합\", 80 이상이면 \"찰떡 궁합\", 70 이상이면 \"좋은 궁합\", 그 외에는 \"무난한 궁합\"으로 판정한다.\n5. 최종 점수, 궁합 단계, 점수 차이를 출력한다.",
        "example": "general = 90\nrelationship = 80\nconflict = 70\nexpression = 85\nexpected_score = \"88\"\n\nfinal_score = (general * 2 + relationship + conflict + expression) / 5\nexpected_score_float = float(expected_score)\ndifference = abs(final_score - expected_score_float)\n\nif final_score >= 90:\n    stage_label = \"운명 궁합\"\nelif final_score >= 80:\n    stage_label = \"찰떡 궁합\"\nelif final_score >= 70:\n    stage_label = \"좋은 궁합\"\nelse:\n    stage_label = \"무난한 궁합\"\n\nprint(\"최종 점수:\", final_score)\nprint(\"궁합 단계:\", stage_label)\nprint(\"예상 점수와의 차이:\", difference)",
        "criteria": ["final_score 계산", "general 2배 반영", "float 사용", "abs 사용", "if/elif/else 사용", "stage_label 또는 같은 역할의 변수 사용", "결과 출력"],
    },
}
